## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per enviornment.
prod_authorizations: &PROD_AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: <%= ENV["RSRS.LDAP.GROUP_BASE"] %>
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    # - cn=admins,ou=groups,dc=test,dc=com
    # - cn=users,ou=groups,dc=test,dc=com
    # If an array is given, the first element will be the attribute to check against, the second the group name
    - ["memberOf", <%= ENV["RSRS.LDAP.USERS.GROUP"] %>]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: user

dev_authorizations: &DEV_AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: "ou=groups,dc=example,dc=org"
  required_groups:
    - ["member", "cn=all,ou=groups,dc=example,dc=org"]
  require_attribute:
    objectClass: inetOrgPerson

## Environment

development:
  host: localhost
  port: 389
  attribute: "cn"
  base: "ou=people,dc=example,dc=org"
  admin_user: "cn=admin,dc=example,dc=org"
  admin_password: "admin"
  ssl: false
  <<: *DEV_AUTHORIZATIONS

#test:
#  host: localhost
#  port: 3389
#  attribute: cn
#  base: ou=people,dc=test,dc=com
#  admin_user: cn=admin,dc=test,dc=com
#  admin_password: admin_password
#  ssl: simple_tls
#  <<: *AUTHORIZATIONS
#
#production:
#  host: <%= ENV["RSRS.LDAP.SERVER"] %>
#  port: 636
#  attribute: samAccountName
#  base: ou=people,dc=test,dc=com
#  admin_user: cn=admin,dc=test,dc=com
#  admin_password: admin_password
#  ssl: start_tls
#  <<: *AUTHORIZATIONS
