# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36c40c8d8dbe1e5d659633902b38ae38457935a627e6d694edf661cb49d37c06abc8139640c74fb67b1ebd0b2f5dc297b8c49cb0038c24a78592d78cdafac95

test:
  secret_key_base: b6db2d548760fce8683927956631c1464a7b67320b28a2716bc27af946bb810438c9b8df1e363b1a9e16f564846d302a3c414475b5f7fcce902ac68af0ba25d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
